version: '3.8'
services:
  mailrun:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      SHEET_ID: "${SHEET_ID}"
    networks:
      - mailbot_network

  maildb:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - mailbot_network

volumes:
  pgdata:

networks:
  mailbot_network:
    driver: bridge
